name: Build App

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当创建针对 main 分支的 PR 时触发
  workflow_dispatch:    # 支持手动触发

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: ⬇️ 检出代码
        uses: actions/checkout@v4
        
      - name: 🔧 构建应用
        run: |
          xcodebuild clean build \
            -project "macPilot.xcodeproj" \
            -scheme "macPilot" \
            -configuration Release \
            -derivedDataPath ./DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
        
      - name: 📤 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: macPilot-app
          path: |
            ./DerivedData/Build/Products/Release/*.app
          if-no-files-found: error
